from ingest import load_faq_data, build_index
documents = load_faq_data()
index = build_index(documents)

INSTRUCTIONS =  '''
Your task is to answer questions from the course participants based on the provided context.

Use the context to find relevant information and provide accurate answers. If the answer is not found in the context, respond with "I don't know."
'''

PROMPT_TEMPLATE = '''
Question:
{question}

Context:
{context}
'''


class RAGBase:

    def __init__(
        self,
        index,
        llm_client,
        instructions=INSTRUCTIONS,
        prompt_template=PROMPT_TEMPLATE,
        course="llm-zoomcamp",
        model="gpt-5.4-mini"
    ):
        self.index = index
        self.llm_client = llm_client
        self.instructions = instructions
        self.course = course
        self.prompt_template = prompt_template
        self.model = model


   # Search function to find relevant documents based on the question and course. This is the first part of the RAG pipeline (def rag(question) above), where we search for relevant documents based on the question. The search function takes a question as input and returns the top 5 relevant documents from the index that match the question and are filtered by the course "llm-zoomcamp".
    def search(self, query, num_results=5):
        boost_dict = {"question": 3.0, "section": 0.5}
        filter_dict = {"course": self.course}

        return self.index.search(
            query,
            num_results=num_results,
            boost_dict=boost_dict,
            filter_dict=filter_dict
        )

    # Build context from search results. This is the second part of the RAG pipeline (def build_context(search_results) above), where we build a context string from the search results. The build_context function takes the search results as input and returns a string that contains the relevant information from the search results, formatted as a context for the LLM to use in generating an answer.
    def build_context(self, search_results):
        lines = []

        for doc in search_results:
            lines.append(doc["section"])
            lines.append("Q: " + doc["question"])
            lines.append("A: " + doc["answer"])
            lines.append("")

        return "\n".join(lines).strip()

    # Build prompt for LLM. This is the third part of the RAG pipeline (def build_prompt(question, search_results) above), where we build a prompt for the LLM to use in generating an answer. The build_prompt function takes the question and search results as input and returns a string that contains the question and context formatted as a prompt for the LLM to use in generating an answer.
    def build_prompt(self, query, search_results):
        context = self.build_context(search_results)
        return self.prompt_template.format(
            question=query, context=context
        )

    # Run LLM to generate answer. This is the fourth part of the RAG pipeline (def llm(instructions, user_prompt, model="gpt-5.4-mini") above), where we run the LLM to generate an answer based on the prompt we built in the previous step. The llm function takes the instructions, user prompt, and model as input and returns the output text generated by the LLM.
    def llm(self, prompt):
        input_messages = [
            {"role": "developer", "content": self.instructions},
            {"role": "user", "content": prompt}
        ]

        response = self.llm_client.responses.create(
            model=self.model,
            input=input_messages
        )

        return response.output_text

    # Put everything together to answer the question. This is the final part of the RAG pipeline (def rag(question) above), where we put everything together to answer the question. The rag function takes a question as input and returns an answer generated by the LLM based on the relevant context found in the search results.
    def rag(self, query):
        search_results = self.search(query)
        prompt = self.build_prompt(query, search_results)
        answer = self.llm(prompt)
        return answer